version: '3'

services:
    orders-db:
      container_name: orders_database
      image: postgres:latest
      restart: always
      volumes:
        - ./postgres:/var/lib/postgresql/data
      ports:
        - 5433:5433
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=orders_db
